//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantPointOfSell.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RPOSDBEntities : DbContext
    {
        public RPOSDBEntities()
            : base("name=RPOSDBEntities")
        {
        }
        public RPOSDBEntities(string connectionString) : base(connectionString)
        {
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_itemGroups> T_itemGroups { get; set; }
        public virtual DbSet<t_items> t_items { get; set; }
        public virtual DbSet<T_appSettings> T_appSettings { get; set; }
        public virtual DbSet<T_invoiceItems> T_invoiceItems { get; set; }
        public virtual DbSet<T_invoice> T_invoice { get; set; }
        public virtual DbSet<T_extra> T_extra { get; set; }
        public virtual DbSet<T_printBillQu> T_printBillQu { get; set; }
    }
}
