//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantPointOfSell.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_invoiceItems
    {
        public int id { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> ItemNo { get; set; }
        public Nullable<double> ItemPrice { get; set; }
        public string ItemComment { get; set; }
        public int id_invoice { get; set; }
    }
}
