//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantPointOfSell.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_items
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<double> price { get; set; }
        public byte[] img { get; set; }
        public Nullable<bool> show { get; set; }
        public Nullable<int> group_id { get; set; }
    }
}
