//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantPointOfSell.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_printBillQu
    {
        public int id { get; set; }
        public Nullable<int> idInvoice { get; set; }
    }
}
